#!/bin/bash
#python2 manage.py syncdb
echo "The next part of the installation requires root permission. Please enter root password to continue."

echo "Creating symlinks to powermonitorweb.server, startupjobs, and logservice..."
curpath=`pwd`
logservice=$curpath'/logservice.py'
startupjobs=$curpath'/startupjobs.py'
powermonitorweb=$curpath'/powermonitorweb.server'
sudo ln -s $logservice /usr/bin/logservice.py
sudo ln -s $startupjosb /usr/bin/startupjobs.py
sudo ln -s $powermonitorweb /usr/bin/powermonitorweb.server
echo "Linking Complete"
# Create and start systemd services for logservice and startupjobs
echo "Enabling and starting systemd startup services..."
sudo cp *.service /etc/systemd/system/
systemctl enable logservice.service
sudo systemctl enable startupjobs.service
sudo systemctl enable powermonitorweb.service
sudo systemctl start logservice.service
sudo systemctl start startupjobs.service
sudo systemctl start powermonitorweb.service
echo "DONE"
